project:
  type: book
  execute-dir: project
  output-dir: ../docs

book:
  title: "hawkesNet"
  subtitle: "An R package for fitting Hawkes network growth models"
  sidebar:
    logo: mini_BA_logo.png
    tools:
      - icon: github
        href: https://github.com/JosephReps/hawkesNet
      - icon: envelope
        href: mailto:joseph.reps@gmail.com
  chapters:
    - index.qmd
    - quick_start.qmd
    - part: "Core Concepts"
      chapters:
      - events.qmd
      - simulation.qmd
      - model_fitting.qmd
      - diagnostics.qmd
    - part: "Kernels & Examples"
      chapters:
        - examples_ba.qmd
        - examples_cs.qmd
        - examples_ba_bip.qmd
        - examples_cs_bip.qmd
    - part: "Writing Custom Kernels"
      chapters:
        - custom_pmf.qmd
        - custom_sim.qmd
    - part: "Sim studies"
      chapters:
        - crime_data.qmd
        - conference_data.qmd
    - part: "Sim studies"
      chapters:
        - ba_study.qmd
        - cs_study.qmd
        - ba_bip_study.qmd
    - references.qmd

format:
  html:
    toc: true
    code-fold: false
    code-tools: false
    css: styles.css

execute:
  echo: true
  message: false
  warning: false
  freeze: auto
